# Generated by Django 5.0.6 on 2024-07-29 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_start', models.DateField(default=None)),
                ('date_end', models.DateField(default=None)),
                ('city', models.CharField(max_length=100)),
                ('plan_result', models.CharField(max_length=100)),
                ('plan_place', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('result_first_place', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('imgage', models.ImageField(blank=True, upload_to='app1/static/img/competition')),
                ('sportsmen', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('programm_name', models.CharField(max_length=100)),
                ('sportsmen', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=None)),
                ('isCompleted', models.BooleanField(blank=True, default=False)),
                ('quantity', models.IntegerField(blank=True, default=None)),
                ('weight', models.FloatField(blank=True, default=None)),
                ('time', models.FloatField(blank=True, default=None)),
                ('time_rest', models.FloatField(blank=True, default=None)),
                ('programm_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.program')),
                ('training_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
    ]
