# Generated by Django 5.0.6 on 2024-07-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='count_approach',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
