# Generated by Django 5.0.6 on 2024-08-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_approach_iscompleted_alter_approach_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='quantity',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='approach',
            name='time',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='approach',
            name='time_rest',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='approach',
            name='weight',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
