# Generated by Django 5.0.6 on 2024-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_approach_quantity_alter_approach_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='approach',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='approach',
            name='time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='approach',
            name='time_rest',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='approach',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
