# Generated by Django 5.0.6 on 2024-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_approach_number_alter_approach_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
