# Generated by Django 4.2.15 on 2024-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_program_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='repeat',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
