# Generated by Django 4.2.15 on 2024-08-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_trainingline_trainingplan_basicapproach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicapproach',
            old_name='programm_id',
            new_name='training_line_id',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='exercise_id',
        ),
    ]
