# Generated by Django 4.2.15 on 2024-08-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_rename_programm_id_basicapproach_training_line_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingline',
            name='type_of_approaches',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
