# Generated by Django 4.2.15 on 2024-08-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_trainingplan_training_line_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingline',
            name='training_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.trainingplan'),
        ),
    ]
