# Generated by Django 4.2.15 on 2024-08-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_remove_trainingline_training_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingline',
            name='training_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.trainingplan'),
        ),
    ]
