# Generated by Django 4.2.15 on 2024-08-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_trainingline_training_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicapproach',
            name='isCompleted',
        ),
    ]
