# Generated by Django 4.2.15 on 2024-08-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0017_remove_basicapproach_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateTimeField()),
                ('training_description', models.CharField(blank=True, max_length=300)),
                ('sportsmen_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_plan_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='training.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='NewTrainingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_approaches', models.CharField(blank=True, max_length=100)),
                ('exercise_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
                ('training_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='training.newtraining')),
            ],
        ),
        migrations.CreateModel(
            name='NewApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.FloatField(blank=True, default=None, null=True)),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('time', models.FloatField(blank=True, default=None, null=True)),
                ('time_rest', models.FloatField(blank=True, default=None, null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('line_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.newtrainingline')),
            ],
        ),
    ]
