# Generated by Django 4.2.15 on 2024-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_newapproach_type_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapproach',
            name='type_temp',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
